/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Control;
import model.Usuario;

/**
 *
 * @author alunolab04
 */
public class sisPlacaMain extends javax.swing.JFrame {
    
    Control control;
    Usuario user;
    /**
     * Creates new form SisPlacaUsuarioEditar
     * @param _control
     */
    public sisPlacaMain(Control _control) {
        control = _control;
        user = control.getUser();
        initComponents();
        
        if(user.getPerfil() != 1){
            menuCadastrar.setEnabled(false);
            menuPesquisar.setEnabled(false);
            menuCarros.setEnabled(false);
            menuProprietarios.setEnabled(false);
        }
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsuarios = new javax.swing.JMenu();
        menuCadastrar = new javax.swing.JMenuItem();
        menuEditar = new javax.swing.JMenuItem();
        menuPesquisar = new javax.swing.JMenuItem();
        menuCarros = new javax.swing.JMenu();
        menuCadastrarCarro = new javax.swing.JMenuItem();
        MenuPesquisarCarros = new javax.swing.JMenuItem();
        menuProprietarios = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SisPlaca - Editar Usuário");

        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jTextPane1.setText("SisPlaca");
        jScrollPane1.setViewportView(jTextPane1);

        menuUsuarios.setText("Usuários");

        menuCadastrar.setText("Cadastrar");
        menuCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuCadastrar);

        menuEditar.setText("Editar");
        menuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuEditar);

        menuPesquisar.setText("Pesquisar");
        menuPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPesquisarActionPerformed(evt);
            }
        });
        menuUsuarios.add(menuPesquisar);

        jMenuBar1.add(menuUsuarios);

        menuCarros.setText("Carros");

        menuCadastrarCarro.setText("Cadastrar");
        menuCadastrarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarCarroActionPerformed(evt);
            }
        });
        menuCarros.add(menuCadastrarCarro);

        MenuPesquisarCarros.setText("Pesquisar");
        menuCarros.add(MenuPesquisarCarros);

        jMenuBar1.add(menuCarros);

        menuProprietarios.setText("Proprietários");

        jMenuItem7.setText("Cadastrar");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menuProprietarios.add(jMenuItem7);

        jMenuItem9.setText("Pesquisar");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        menuProprietarios.add(jMenuItem9);

        jMenuBar1.add(menuProprietarios);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarActionPerformed
        new SisPlacaUsuarioCadastrar(control).setVisible(true);
    }//GEN-LAST:event_menuCadastrarActionPerformed

    private void menuPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPesquisarActionPerformed
        new SisPlacaUsuarioPesquisar(control).setVisible(true);
    }//GEN-LAST:event_menuPesquisarActionPerformed

    private void menuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarActionPerformed
        new SisPlacaUsuarioEditar(control, this.user).setVisible(true);
    }//GEN-LAST:event_menuEditarActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        new SisPlacaProprietarioCadastrar(control).setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new SisPlacaProprietarioPesquisar(control).setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void menuCadastrarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarCarroActionPerformed
        // TODO add your handling code here:
         new SisPlacaCarroCadastrar(control).setVisible(true);
    }//GEN-LAST:event_menuCadastrarCarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sisPlacaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sisPlacaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sisPlacaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sisPlacaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuPesquisarCarros;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JMenuItem menuCadastrar;
    private javax.swing.JMenuItem menuCadastrarCarro;
    private javax.swing.JMenu menuCarros;
    private javax.swing.JMenuItem menuEditar;
    private javax.swing.JMenuItem menuPesquisar;
    private javax.swing.JMenu menuProprietarios;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
