/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Control;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.Timer;
import model.Carro;
import model.Proprietario;

/**
 *
 * @author alunolab04
 */
public class SisPlacaCarroEditar extends javax.swing.JFrame {

    Control control;
    byte[] fotoCarro = null;
    Carro carro;

    /**
     * Creates new form SisPlacaUsuarioCadastrar
     *
     * @param _control
     * @param _c
     */
    public SisPlacaCarroEditar(Control _control, Carro _c) {
        control = _control;
        //Reseta carro antes de comecar cadastro de novo carro.
        Control.carroControl.carro = _c;
        this.carro = _c;

        initComponents();
        TxMessage2.setText(" ");
        setValues(this.carro);

        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE); 
    }

    /**
     * Fecha janela.
     */
    private void fecha() {
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        LbPlaca = new javax.swing.JLabel();
        BtSalvar = new javax.swing.JButton();
        TxPlaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        LbMarca = new javax.swing.JLabel();
        LbModelo = new javax.swing.JLabel();
        TxMarca = new javax.swing.JTextField();
        TxModelo = new javax.swing.JTextField();
        LbCor = new javax.swing.JLabel();
        TxCor = new javax.swing.JTextField();
        LbMensagem = new java.awt.Label();
        BtCancelar = new javax.swing.JButton();
        BtImagem = new java.awt.Button();
        LbFoto = new javax.swing.JLabel();
        foto = new javax.swing.JLabel();
        BtAddProprietarios = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelProprietarios = new javax.swing.JPanel();
        BtDeletar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        TxMessage2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SisPlaca - Editar Carro");

        LbPlaca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LbPlaca.setText("PLACA *");

        BtSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtSalvar.setText("SALVAR");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        TxPlaca.setName(""); // NOI18N
        TxPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxPlacaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("EDITAR CARRO");

        LbMarca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LbMarca.setText("MARCA *");

        LbModelo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LbModelo.setText("MODELO *");

        TxMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxMarcaActionPerformed(evt);
            }
        });

        TxModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxModeloActionPerformed(evt);
            }
        });

        LbCor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LbCor.setText("COR *");

        TxCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxCorActionPerformed(evt);
            }
        });

        LbMensagem.setAlignment(java.awt.Label.CENTER);
        LbMensagem.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        LbMensagem.setForeground(new java.awt.Color(255, 0, 0));
        LbMensagem.setText(" ");

        BtCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtCancelar.setText("CANCELAR");
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        BtImagem.setActionCommand("imageSelect");
        BtImagem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtImagem.setLabel("SELECIONAR IMAGEM");
        BtImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtImagemActionPerformed(evt);
            }
        });

        LbFoto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LbFoto.setText("FOTO *");

        foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        BtAddProprietarios.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtAddProprietarios.setText("ADICIONAR PROPRIETÁRIO");
        BtAddProprietarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAddProprietariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelProprietariosLayout = new javax.swing.GroupLayout(PanelProprietarios);
        PanelProprietarios.setLayout(PanelProprietariosLayout);
        PanelProprietariosLayout.setHorizontalGroup(
            PanelProprietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        PanelProprietariosLayout.setVerticalGroup(
            PanelProprietariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(PanelProprietarios);

        BtDeletar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtDeletar.setForeground(new java.awt.Color(255, 0, 51));
        BtDeletar.setText("EXCLUIR");
        BtDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDeletarActionPerformed(evt);
            }
        });

        TxMessage2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TxMessage2.setText("LABEL");
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxCor, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(LbMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxMarca)
                                    .addComponent(LbCor, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(BtAddProprietarios))))
                    .addComponent(jSeparator3)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(BtSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtDeletar)
                        .addGap(18, 18, 18)
                        .addComponent(BtCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addComponent(TxMessage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbFoto)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbMarca)
                            .addComponent(LbPlaca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LbModelo)
                                    .addComponent(LbCor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtAddProprietarios))
                                .addGap(11, 11, 11)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(foto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(BtImagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(TxMessage2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtCancelar)
                            .addComponent(BtDeletar)
                            .addComponent(BtSalvar))))
                .addContainerGap())
        );

        LbModelo.getAccessibleContext().setAccessibleName("Sobrenome");

        getAccessibleContext().setAccessibleName("SisPlaca - Cadastrar Carro");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxPlacaActionPerformed

    private void TxMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxMarcaActionPerformed

    private void TxModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxModeloActionPerformed

    private void TxCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxCorActionPerformed

    /**
     *
     * @param evt
     */
    @SuppressWarnings("empty-statement")
    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        //Receber valores de view
        //Informacoes de Carro
        String placa = TxPlaca.getText();
        String marca = TxMarca.getText();
        String modelo = TxModelo.getText();
        String cor = TxCor.getText();

        //Checagem de valores
        if (placa.isEmpty() || marca.isEmpty() || modelo.isEmpty()
                || cor.isEmpty() || fotoCarro == null) {
            TxMessage2.setText("Os campos marcados com asterisco não podem estar vazios.");
        } else {
            Carro novoCarro = new Carro(carro.getId(), placa, marca, modelo, cor, 1, fotoCarro, Control.carroControl.carro.getProprietarios());

            int result = Control.carroControl.alterarCarro(novoCarro);

            switch (result) {
                case -1: {
                    LbMensagem.setForeground(Color.red);
                    LbMensagem.setText("Ao menos um proprietário requerido.");
                    break;
                }
                case 0: {
                    LbMensagem.setForeground(Color.red);
                    LbMensagem.setText("Algum erro aconteceu.");
                    break;
                }
                case 1: {
                    LbMensagem.setText("Carro salvo com sucesso");
                    LbMensagem.setForeground(Color.blue);

                    Timer timer = new Timer(1500, new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent e) {
                            fecha();
                        }
                    });
                    timer.start();
                    break;
                }
            };
        }
    }//GEN-LAST:event_BtSalvarActionPerformed

    /**
     * Fecha janela de cadastrar carro.
     *
     * @param evt
     */
    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        this.fecha();
    }//GEN-LAST:event_BtCancelarActionPerformed

    /**
     * Escreve nome de proprietarios selecionados e botao para excluir qualquer
     * um deles.
     *
     * @param _proprietarios
     */
    private void adicionarProprietarios(ArrayList<Proprietario> _proprietarios) {
        int i = 1;

        //Lima panel antes de recolocar proprietarios selecionados
        PanelProprietarios.removeAll();

        for (final Proprietario p : _proprietarios) {
            //Cria novo label para nome do proprietario
            JLabel label = new JLabel();
            label.setText(p.getNome() + " " + p.getSobrenome()); //seta texto
            label.setName("LbProprietario" + i);   //seta nome de label
            label.setSize(label.getPreferredSize()); //seta tamanho
            label.setLocation((int) label.getLocation().getX() + 50,
                    (int) label.getLocation().getY() + (30 * i));//seta localizacaao

            //Cria novo botao
            JButton button = new JButton();
            button.setName("BtProprietario" + i);
            button.setText("Excluir");
            button.setSize(button.getPreferredSize());

            //Adiciona listener para retirar prorpietario de panel do panel
            button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    retiraProprietario(p);
                }
            });
            //end listener

            button.setLocation((int) label.getLocation().getX() + 200, (int) label.getLocation().getY());

            if (i > 5) {
                PanelProprietarios.setPreferredSize(new Dimension(PanelProprietarios.getPreferredSize().width,
                        PanelProprietarios.getPreferredSize().height + 30));
            }

            //Adiciona novo botao ao panel
            PanelProprietarios.add(label);
            PanelProprietarios.add(button);
            //end adiciona novo botao ao panel
            i++;
        }
        //revalida e repinta apenas apos adicionar todos proprietarios
        PanelProprietarios.revalidate();
        PanelProprietarios.repaint();
    }

    /**
     * Retira proprietario de lista de proprietarios de carro.
     *
     * @param _p
     */
    private void retiraProprietario(Proprietario _p) {
        Control.carroControl.carro.getProprietarios().remove(_p);
        adicionarProprietarios(Control.carroControl.carro.getProprietarios());
    }

    /**
     * Seleciona imagem a mostra em jlabel.
     *
     * @param evt
     */
    private void BtImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtImagemActionPerformed
        JFileChooser fileChooser = new JFileChooser();   //Cria o objeto do tipo Janela JFileChooser    
        fileChooser.setDialogTitle("Escolha a Foto do Carro");  //Define o título do JFileChooser    
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);  //Define que só serão abertos arquivos    
        {
            if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                try {
                    File arquivo = fileChooser.getSelectedFile();//arquivo    
                    BufferedImage bi = ImageIO.read(arquivo); //carrega a imagem real num buffer 

                    //Add image in byte[] format
                    ByteArrayOutputStream baos = new ByteArrayOutputStream();
                    ImageIO.write(bi, "jpg", baos);
                    baos.flush();
                    fotoCarro = baos.toByteArray();
                    //end

                    BufferedImage aux = new BufferedImage(210, 170, bi.getType());//cria um buffer auxiliar com o tamanho desejado    
                    Graphics2D g = aux.createGraphics();//pega a classe graphics do aux para edicao    
                    AffineTransform at = AffineTransform.getScaleInstance((double) 210 / bi.getWidth(), (double) 170 / bi.getHeight());//cria a transformacao    
                    g.drawRenderedImage(bi, at);//pinta e transforma a imagem real no auxiliar    
                    foto.setIcon(new ImageIcon(aux));//seta no jlabel   
                    foto.setText(null); //Seta texto de jlabel nulo
                } catch (IOException ex) {
                    //ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_BtImagemActionPerformed

    /**
     * Abre pop-up para selecao de proprietario do carro e seta catch de evento.
     *
     * @param evt
     */
    private void BtAddProprietariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAddProprietariosActionPerformed
        SisPlacaCarroEditarProprietario carroProprietario = new SisPlacaCarroEditarProprietario(control);
        carroProprietario.setVisible(true);

        //Recupera o evento de quando o pop-up é fechado para 
        //atualizar lista de proprietarios selecionados
        carroProprietario.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent evento) {
                adicionarProprietarios(Control.carroControl.carro.getProprietarios());
            }
        });
    }//GEN-LAST:event_BtAddProprietariosActionPerformed

    private void BtDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDeletarActionPerformed
        String msg = Control.carroControl.deletarCarro(this.carro);
        LbMensagem.setText(msg);
        LbMensagem.setForeground(Color.blue);
        Timer timer = new Timer(1500, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                fecha();
            }
        }
        );
        timer.start();
    }//GEN-LAST:event_BtDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SisPlacaCarroEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    /**
     * Seta valores de carro para ser mostrado em tela de exibicao.
     * @param _carro 
     */
    private void setValues(Carro _carro) {
        
        //Seta dados de carro nnos campos da janela
        TxCor.setText(_carro.getCor());
        TxMarca.setText(_carro.getMarca());
        TxModelo.setText(_carro.getModelo());
        TxPlaca.setText(_carro.getPlaca());
        TxPlaca.setEnabled(false);
        //Adiciona lista de proprietarios
        adicionarProprietarios(_carro.getProprietarios());

        //Seta foto de caror.
        try {
            InputStream in = new ByteArrayInputStream(_carro.getFoto());//carrega imagem de banco de dados em buffer
            fotoCarro = _carro.getFoto();
            BufferedImage bi = ImageIO.read(in);//carrega imagem bufferizada
            BufferedImage aux = new BufferedImage(210, 170, 5);//cria um buffer auxiliar com o tamanho desejado    
            Graphics2D g = aux.createGraphics();//pega a classe graphics do aux para edicao    
            AffineTransform at = AffineTransform.getScaleInstance((double) 210 / bi.getWidth(), (double) 170 / bi.getHeight());//cria a transformacao    
            g.drawRenderedImage(bi, at);//pinta e transforma a imagem real no auxiliar    
            foto.setIcon(new ImageIcon(aux));//seta no jlabel   
            foto.setText(null); //Seta texto de jlabel nulo
        } catch (Exception ex) {
            // ex.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAddProprietarios;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtDeletar;
    private java.awt.Button BtImagem;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JLabel LbCor;
    private javax.swing.JLabel LbFoto;
    private javax.swing.JLabel LbMarca;
    private java.awt.Label LbMensagem;
    private javax.swing.JLabel LbModelo;
    private javax.swing.JLabel LbPlaca;
    private javax.swing.JPanel PanelProprietarios;
    private javax.swing.JTextField TxCor;
    private javax.swing.JTextField TxMarca;
    private javax.swing.JLabel TxMessage2;
    private javax.swing.JTextField TxModelo;
    private javax.swing.JTextField TxPlaca;
    private javax.swing.JLabel foto;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
