-- MySQL Script generated by MySQL Workbench
-- Wed Apr  8 16:12:41 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sisplaca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisplaca` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sisplaca` ;

-- -----------------------------------------------------
-- Table `sisplaca`.`tb_carros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisplaca`.`tb_carros` (
  `cl_id` INT NOT NULL AUTO_INCREMENT,
  `cl_placa` VARCHAR(45) NOT NULL,
  `cl_marca` VARCHAR(45) NOT NULL,
  `cl_modelo` VARCHAR(45) NOT NULL,
  `cl_cor` VARCHAR(45) NOT NULL,
  `cl_foto` BLOB NULL,
  `cl_ativo` INT(1) NULL,
  PRIMARY KEY (`cl_id`),
  UNIQUE INDEX `id_UNIQUE` (`cl_id` ASC),
  INDEX `placa_INDEX` (`cl_placa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisplaca`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisplaca`.`tb_usuarios` (
  `cl_id` INT NOT NULL AUTO_INCREMENT,
  `cl_login` VARCHAR(45) NOT NULL,
  `cl_senha` VARCHAR(255) NOT NULL,
  `cl_nome` VARCHAR(45) NOT NULL,
  `cl_nomeDomeio` VARCHAR(45) NULL,
  `cl_sobrenome` VARCHAR(45) NOT NULL,
  `cl_perfil` INT(1) NOT NULL COMMENT '0 - usuario' /* comment truncated */ /*1 - administrador
*/,
  `cl_email` VARCHAR(45) NOT NULL,
  `cl_sexo` CHAR NOT NULL,
  `cl_telefone` VARCHAR(45) NOT NULL,
  `cl_ativo` INT(1) NULL,
  PRIMARY KEY (`cl_id`),
  UNIQUE INDEX `cl_id_UNIQUE` (`cl_id` ASC, `cl_email` ASC),
  UNIQUE INDEX `cl_login_UNIQUE` (`cl_login` ASC),
  INDEX `indexes` (`cl_login` ASC, `cl_nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisplaca`.`tb_proprietarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisplaca`.`tb_proprietarios` (
  `cl_id` INT NOT NULL AUTO_INCREMENT,
  `cl_nome` VARCHAR(45) NOT NULL,
  `cl_nomeDoMeio` VARCHAR(45) NULL,
  `cl_sobrenome` VARCHAR(45) NOT NULL,
  `cl_sexo` CHAR NOT NULL,
  `cl_nascimento` DATETIME NULL,
  `cl_foto` BLOB NOT NULL,
  `cl_email` VARCHAR(255) NOT NULL,
  `cl_telefone` VARCHAR(45) NOT NULL,
  `cl_endereco` VARCHAR(255) NOT NULL,
  `cl_ativo` INT(1) NOT NULL,
  PRIMARY KEY (`cl_id`),
  UNIQUE INDEX `cl_id_UNIQUE` (`cl_id` ASC),
  INDEX `cl_nome_index` (`cl_nome` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sisplaca`.`tb_proprietarios_carros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisplaca`.`tb_proprietarios_carros` (
  `cl_proprietarios` INT NOT NULL,
  `cl_carros` INT NOT NULL,
  PRIMARY KEY (`cl_proprietarios`, `cl_carros`),
  INDEX `fk_tb_proprietarios_has_tb_carros1_tb_carros1_idx` (`cl_carros` ASC),
  INDEX `fk_tb_proprietarios_has_tb_carros1_tb_proprietarios1_idx` (`cl_proprietarios` ASC),
  CONSTRAINT `fk_tb_proprietarios_has_tb_carros1_tb_proprietarios1`
    FOREIGN KEY (`cl_proprietarios`)
    REFERENCES `sisplaca`.`tb_proprietarios` (`cl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_proprietarios_has_tb_carros1_tb_carros1`
    FOREIGN KEY (`cl_carros`)
    REFERENCES `sisplaca`.`tb_carros` (`cl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO tb_usuarios VALUES (1, 'admin', password('admin'), 'Administrador', '', 'Administador', 1, 'adm@adm.com', 'M', '999999', 1);
